site_name: SPAN
repo_url: https://github.com/danielegasparri/span-gui
docs_dir: docs
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Quick start: quick_start.md
  - Long-slit spectra extraction: long-slit_extraction.md
  - Datacube spectra extraction: datacube_extraction.md
  - Spectra manipulation: spectra_manipulation.md
  - Spectral analysis overview: spectral_analysis_overview.md
  - Line-strength analysis: linestrength.md
  - Stars and gas kinematics: stars_and_gas_kinematics.md
  - Stellar populations and SFH: stellar_populations_and_SFH.md
  - Plotting 2D data: plot_data.md
  - Plotting 2D maps: plot_maps.md
  - Tips and Tricks: tips_and_tricks.md
  - User Manual: manual.md
  - Changelog: changelog.md
  - License: LICENSE.md
